### ISSUE TITLE
t_mat in OrbitFG

### ISSUE THREAD

**Issue by slowakp** [cntaylor/factorGraph2DsatelliteExample#2]
https://github.com/cntaylor/factorGraph2DsatelliteExample/blob/89cec0b85d0711625cda72757747d05af7cfc99a/OrbitFG.py#L162

Hello, 
Could you double chceck if there is an error in:

            t_mat = np.array([[-self.prop_dt*(y**2-2*x**2)/2, here>  3*x*y*self.prop_dt <here, 0, 0],
                              [3*x*y*self.prop_dt/2.0, -self.prop_dt*(x**2-2*y**2)/2, 0, 0],
                              [2*x**2-y**2, 3*x*y, 0, 0],
                              [3*x*y, 2*y**2-x**2, 0, 0]])
Shouldn't it be divided by 2.0? ==> 3*x*y*self.prop_dt/2.0

I am working on your code to run it in matlab and found an incosistency when comparing your code for F with the results of my script written using matlab symbolic toolbox:

  clear
```
  syms x y vx vy GE dt real
  state = [x; y; vx; vy];
  A = [1 0 dt 0;
      0 1 0 dt;
      0 0 1 0;
      0 0 0 1];
  f(x,y,vx,vy) = A*state - GE * dt /(x^2+y^2)^(3/2) * [x*dt/2; y*dt/2; x; y]
  J = jacobian(f,[x,y,vx,vy])
```

% from python
  ```
k = dt*GE/( (x^2 + y^2)^(5/2) );
  tMat= ...
      [-dt*(y^2-2*x^2)/2, 3*x*y*dt/2, 0, 0;
      3*x*y*dt/2.0, -dt*(x^2-2*y^2)/2, 0, 0;
      2*x^2-y^2, 3*x*y, 0, 0;
      3*x*y, 2*y^2-x^2, 0, 0];
  F = A + k * tMat;


simplify(F - J) % does not equal zeros unless the above mentioned element is divided by two.
```
Kind regards
Paweł Słowak

**Comment by cntaylor** [comment]
Unfortunately, you are correct. :)  Equation (7) in the description has it as a /2.

**Comment by cntaylor** [comment]
Made the change in the code, and the slide example has no visible difference

**Comment by slowakp** [comment]
Thank you for your prompt response! I appreciate the repository—it has been very helpful.
